import "./globals.css";
import { Montserrat } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const montserrat = Montserrat({
  subsets: ["latin"],
  weights: [400, 700],
  variable: "--font-montserrat",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} mx-16`}>{children}</body>
    </html>
  );
}
