import "./globals.css";
import { Montserrat } from "next/font/google";
import Nav from "./Nav";
import Image from "next/image";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const montserrat = Montserrat({
  subsets: ["latin"],
  weights: [400, 700],
  variable: "--font-montserrat",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}`}>
        <Nav />
        <div className="mx-16">{children}</div>
        <footer className="flex mt-32 justify-end items-center p-8">
          <p className=" text-sm pr-1">Website built using: </p>
          <a href="https://www.themoviedb.org/">
            <Image
              src="/themoviedb_logo.svg"
              alt="The Movie DB Logo"
              width="100"
              height="50"
            />
          </a>
        </footer>
      </body>
    </html>
  );
}
